# --- Redirects for Flutter Web (SPA) ---
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# --- Base settings ---
[build]
  # Tell Netlify where Flutter's web output is.
  publish = "build/web"
  command = "bash build.sh"

# --- Flutter Plugin ---
#[[plugins]]
#package = "netlify-plugin-flutter"
#  [plugins.inputs]
#  channel = "stable"