name: nextbus
description: "An App to store bus timing and to show when next bus will come"
publish_to: 'none' # Prevents accidental publishing to pub.dev

version: 2.1.0-beta

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # Firebase Services
  firebase_core: ^4.2.1
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  firebase_crashlytics: ^5.0.4
  firebase_performance: ^0.11.1+2
  cloud_firestore: ^6.1.0

  # Google Sign-In
  google_sign_in: 6.3.0

  # State Management & Local Storage
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3

  # Networking
  connectivity_plus: ^7.0.0
  dio: ^5.9.0
  internet_connection_checker_plus: ^2.9.0

  # UI & Utilities
  cupertino_icons: ^1.0.8
  dynamic_color: ^1.8.1
  intl: ^0.20.2
  package_info_plus: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.14.4

# Flutter-specific configurations
flutter:

  uses-material-design: true

  assets:
    - assets/logo_new.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

#  dart run flutter_launcher_icons
flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo_new.png"
  adaptive_icon_background: "#039AE4"
  adaptive_icon_foreground: "assets/logo_new_fg.png"
  web:
    generate: true

#  dart run launcher_name:main
launcher_name:
  default: "Next Bus"
