name: nextbus
description: "An App to store bus timing and to show when next bus will come"
publish_to: 'none'

version: 1.2.1-beta

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_slidable: ^4.0.1
  dynamic_color: ^1.8.1
  provider: ^6.1.5+1
  intl: ^0.20.2
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  shared_preferences: ^2.5.3
  dio: ^5.9.0
  google_sign_in: 6.3.0
  internet_connection_checker_plus: ^2.9.0
  firebase_crashlytics: ^5.0.3
  firebase_analytics: ^12.0.3
  firebase_performance: ^0.11.1+1
  connectivity_plus: ^7.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  launcher_name: ^1.0.2
  flutter_launcher_icons: ^0.14.4


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo_new.png"
  adaptive_icon_background: "#039AE4"
  adaptive_icon_foreground: "assets/logo_new_fg.png"
  web:
    generate: true
  windows:
    generate: true
#  dart run flutter_launcher_icons

launcher_name:
  default: "Next Bus"
#  dart run launcher_name:main
