# This setting prevents people from opening a blank issue.
# It forces them to choose one of your templates.
blank_issues_enabled: false

# These are links that will appear on the "New Issue" page.
contact_links:
  - name: ðŸ“– Project Documentation
    url: https://github.com/Sourish-Kanna/Next-Bus-Frontend/blob/main/README.md
    about: Please check the README for project info before creating an issue.