name: Build and Upload Releases

on:
  release:
    types: [published, drafted]

jobs:
  build-and-upload-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Flutter ðŸ¦
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build APK ðŸ“¦
        run: >
          flutter build apk --release
          --build-name ${{ github.event.release.tag_name }}
          --build-number ${{ github.run_number }}
          --dart-define=API_LINK=${{ secrets.API_LINK }}

      - name: Rename APK file
        id: rename_apk
        run: |
          APK_NAME="Next-Bus-${{ github.event.release.tag_name }}.apk"
          APK_PATH="build/app/outputs/flutter-apk/$APK_NAME"
          mv build/app/outputs/flutter-apk/app-release.apk "$APK_PATH"
          echo "path=$APK_PATH" >> "$GITHUB_OUTPUT"
          echo "name=$APK_NAME" >> "$GITHUB_OUTPUT"

      - name: Upload APK to this Release ðŸš€
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.rename_apk.outputs.path }}

  build-and-upload-windows:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository at release tag
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.release.tag_name }}

      - name: Set up Flutter ðŸ¦
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Build Windows Executable ðŸ“¦
        run: >
          flutter build windows --release
          --build-name ${{ github.event.release.tag_name }}
          --build-number ${{ github.run_number }}
          --dart-define=API_LINK=${{ secrets.API_LINK }}

      - name: Zip the Release folder
        id: zip_release
        run: |
          $RELEASE_PATH = "build\windows\x64\runner\Release"
          $ZIP_NAME = "Next-Bus-Windows-${{ github.event.release.tag_name }}.zip"
          Compress-Archive -Path $RELEASE_PATH\* -DestinationPath $ZIP_NAME
          echo "path=$ZIP_NAME" >> $env:GITHUB_OUTPUT
        shell: powershell

      - name: Upload Windows ZIP to this Release ðŸš€
        uses: softprops/action-gh-release@v2
        with:
          files: ${{ steps.zip_release.outputs.path }}

